---
pagetitle: "Trafford Annual Report plots"
output:
  html_document:
    theme: bootstrap
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dev = 'svg')

library(tidyverse) ;  library(sf) ; library(httr) ; library(readxl); library(fingertipsR) ; library(scales) ; library(ggtext) ; library(ggrepel)

boundary <- st_read("https://github.com/traffordDataLab/spatial_data/raw/master/local_authority/2016/trafford_local_authority_generalised.geojson")
```

<br />

<div class="row">
<div class="col-md-6">
```{r}
### New properties by Council tax band
council_tax_bands <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/housing/council_tax_bands.csv") %>% 
  filter(area_name == "Trafford")

ggplot(council_tax_bands, aes(x = fct_rev(band), y = value, fill = area_name)) +
  geom_col(fill = "#007C9E") +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_label(aes(label = percent(value, accuracy = 1)),
             colour = "#000000", fill = NA, label.size = NA, 
             size = 4, hjust = 0, vjust = 0.5) +
  scale_x_discrete(expand = c(0.005, 0.005)) +
  scale_y_continuous(expand = c(0.005, 0.005)) +
  labs(x = NULL, y = NULL,
       title = "Properties by council tax band",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, percentage built between 2010 and 2019	</span>"),
       caption = "Source: Valuation Office Agency") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        axis.text.x = element_blank(),
        axis.text.y = element_text(face = "bold", size = 10)) +
  coord_flip() +
  expand_limits(y = c(0, 0.28))

ggsave("outputs/council_tax_bands.eps", device = "eps")
```
</div>

<div class="col-md-6">
```{r}
### Healthy life expectancy at birth
healthy_life_expectancy_at_birth <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/health/healthy_life_expectancy_at_birth.csv") %>% 
  filter(area_name == "Trafford")

ggplot(healthy_life_expectancy_at_birth,
       aes(x = period, y = value, colour = group, group = group)) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  scale_colour_manual(values = c("Female" = "#A35A50", "Male" = "#ED9B37")) +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(55,70), breaks = seq(55,70,5), position = "right") +
  labs(x = NULL, y = NULL,
       title = "Healthy life expectancy at birth",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, number of years</span>"),
       caption = "Source: Office for National Statistics",
       colour = NULL
       ) +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        legend.position = c(0.8, 1.05),
        legend.direction = "horizontal",
        legend.text = element_text(size = 8),
        axis.text.x = element_text(angle = 90))

ggsave("outputs/healthy_life_expectancy_at_birth.eps", device = "eps")
```
</div>
</div>

<div class="row">
<div class="col-md-6">
```{r}
### Adult smoking prevalence
smoking_adults <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/health/smoking_adults.csv") %>% 
  mutate(period = as_factor(period),
         value = value/100)

ggplot(data = filter(smoking_adults, area_name != "England"), aes(x = period, y = value)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  stat_boxplot(geom = "errorbar", colour = "#C9C9C9", width = 0.2) +
  geom_boxplot(colour = "#C9C9C9", fill = "#C9C9C9", alpha = 0.5, outlier.shape = 21, outlier.colour = "#C9C9C9", outlier.size = 1, fatten = NULL) +
  geom_boxplot(data = filter(smoking_adults, area_name == "England"),
               aes(x = factor(period), y = value),
               fill = "#C9C9C9", size = 0.3) +
  geom_point(data = filter(smoking_adults, area_name == "Trafford"), 
             aes(x = period, y = value, fill = significance), 
             shape = 21, colour = "#000000", size = 3)  +
  scale_x_discrete(expand = c(0.005, 0.005)) +
  scale_fill_manual(values = c("Better" = "#92D050",
                               "Similar" = "#FFC000",
                               "Worse" = "#C00000")) +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, NA), 
                     labels = percent_format(accuracy = 1), position = "right") +
  labs(x = NULL, y = NULL,
       title = "Smoking prevalence in adults (18+)",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, percentage</span>"),
       caption = "Source: Annual Population Survey",
       fill = "Compared with England:") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        legend.position = c(0.8, 1.05),
        legend.direction = "horizontal",
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(angle = 90))

ggsave("outputs/smoking_adults.eps", device = "eps")
```
</div>
  
<div class="col-md-6">
```{r}
### Apprenticeship starts
apprenticeships <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/places/apprenticeships.csv")

ggplot(filter(apprenticeships, area_name == "Trafford"),
       aes(x = period, y = value)) +
  geom_col(fill = "#007C9E") +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, NA), label = comma, position = "right") +
  labs(x = NULL, y = NULL,
    title = "Apprenticeship starts",
    subtitle = paste0("<span style = 'color:#757575;'>Trafford, number of starts</span>"),
    caption = "Source: Department for Education") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.ontop = TRUE,            
        panel.background = element_rect(color = NA, fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)))

ggsave("outputs/apprenticeships.eps", device = "eps")
```
</div>
</div>

<div class="row">
<div class="col-md-6">
```{r}
### Children living in poverty

# Source: End Child Poverty / HMRC
# URL: http://www.endchildpoverty.org.uk/local-child-poverty-data-201415-20189

# tmp <- tempfile(fileext = ".xlsx")
# GET(url = "http://www.endchildpoverty.org.uk/wp-content/uploads/2020/05/local-CP-BHC-2014-15-to-18-19-2.xlsx",
#     write_disk(tmp))
# 
# child_poverty <- read_xlsx(tmp, sheet = 1, skip = 4) %>% 
#   rename(area_name = `...1`) %>% 
#   filter(area_name == "Trafford") %>% 
#   select(-`Percentage point increase, 2014/15 to 2018/19`) %>% 
#   pivot_longer(-area_name, names_to = "period", values_to = "value")

child_poverty <- read_csv("data/child_poverty.csv")

ggplot(child_poverty, aes(x = period, y = value)) +
  geom_col(fill = "#007C9E") +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, NA), labels = percent_format(accuracy = 1), position = "right") +
  labs(x = NULL, y = NULL,
       title = "Children living in poverty",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, percent in households below 60% median before housing costs</span>"),
       caption = "Source: End Child Poverty") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.ontop = TRUE,            
        panel.background = element_rect(color = NA, fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)))

ggsave("outputs/child_poverty.eps", device = "eps")
```
</div>
  
<div class="col-md-6">
```{r}
### Children in care
# Source: Department for Education
# URL: https://fingertips.phe.org.uk/profile/child-health-profiles

children_in_care <- fingertips_data(IndicatorID = 90803, AreaTypeID = 102, rank = TRUE) %>% 
  filter(AreaName == "Trafford") %>% 
  select(area_code = AreaCode,
         area_name = AreaName,
         period = Timeperiod,
         value = Value,
         significance = ComparedtoEnglandvalueorpercentiles) %>%
  mutate(indicator = "Children in care: rate per 10,000 population aged < 18",
         measure = "per 10,000",
         unit = "Persons",
         value = round(value, 1))

ggplot(children_in_care, 
       aes(x = period, y = value, colour = area_name, group = area_name)) +
  geom_line(colour = "#C9C9C9", size = 1) +
  geom_point(aes(fill = significance), shape = 21, colour = "#000000", size = 3) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  scale_fill_manual(values = c("Better" = "#92D050",
                               "Similar" = "#FFC000",
                               "Worse" = "#C00000")) +
  scale_y_continuous(limits = c(0, 80), labels = comma, position = "right") +
  labs(x = NULL, y = NULL,
       title = "Children in care",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, rate per 10,000 aged under 18 years</span>"),
       caption = "Source: Department for Education",
       fill = "Compared with England:") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        legend.position = c(0.8, 1.05),
        legend.direction = "horizontal",
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(angle = 90))

ggsave("outputs/children_in_care.eps", device = "eps")
```
</div>
</div>

<div class="row">
<div class="col-md-6">
```{r}
### NEETS

neets <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/children/neets.csv") %>% 
  filter(area_name == "Trafford") %>% 
  mutate(value = value/100)

ggplot(neets, aes(x = period, y = value)) +
  geom_col(fill = "#007C9E") +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_label(aes(label = percent(value, accuracy = 1)),
             colour = "#000000", fill = NA, label.size = NA, 
             size = 4, hjust = 0, vjust = 0.5) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(x = NULL, y = NULL,
       title = "16-17 year olds not in education, employment or training",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, percentage</span>"),
       caption = "Source: Department for Education") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        axis.text.x = element_blank(),
        axis.text.y = element_text(face = "bold", size = 10, margin = margin(r = -13))) +
  coord_flip() +
  expand_limits(y = c(0, 0.07))

ggsave("outputs/neets.eps", device = "eps")
```
</div>
  
<div class="col-md-6">
```{r}
### Recycled household waste

recycling <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/pride/recycling.csv") %>% 
  filter(area_name == "Trafford")

ggplot(recycling, aes(x = period, y = value, group = area_name)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_line(colour = "#007C9E", size = 1) +
  geom_point(fill = "#007C9E", shape = 21, size = 2.5, colour = "white") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, NA), labels = percent_format(accuracy = 1), position = "right") +
  labs(x = NULL, y = NULL,
       title = "Recycled household waste",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, percentage</span>"),
       caption = "Source: DEFRA") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10))) 

ggsave("outputs/recycling.eps", device = "eps")
```
</div>
</div>

<div class="row">
<div class="col-md-6">
```{r}
### Potholes

potholes <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/pride/potholes.csv") %>% 
  filter(area_name == "Trafford")

ggplot(potholes, aes(x = period, y = value, group = area_name)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_line(colour = "#007C9E", size = 1) +
  geom_point(fill = "#007C9E", shape = 21, size = 2.5, colour = "white") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, 400), labels = comma, position = "right") +
  labs(x = NULL, y = NULL,
       title = "Potholes",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, number of reports</span>"),
       caption = "Source: fixmystreet.com") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10))) 

ggsave("outputs/potholes.eps", device = "eps")
```
</div>
  
<div class="col-md-6">
```{r}
### Green flag awards

green_flags <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/green/green_flags.csv") %>% 
  filter(area_name == "Trafford") %>% 
  mutate(name = str_replace(name, " \\(.*\\)", ""))

ggplot(data = green_flags, aes(x = lon, y = lat)) +
  geom_sf(data = boundary, fill = "#E7E7E7", color = "#C4C4C4") +
  geom_point(size = 4, shape = 21, fill = "#7EA52E", colour = "#FFFFFF") +
  geom_text_repel(aes(label = name), size = 3, point.padding = 0.5) +
  labs(x = NULL, y = NULL, 
       title = "Green Flag Awards",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, 2019/20 winners</span>"),
       caption = "Source: MHCLG \nContains Ordnance Survey data © Crown copyright and database right 2020",
       fill = NULL) +
  coord_sf(datum = NA) +
  theme_void() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, lineheight = 1.2),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10))) 

ggsave("outputs/green_flags.eps", device = "eps")
```
</div>
</div>

<div class="row">
<div class="col-md-6">
```{r}
### CO2 emissions

co2_emissions <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/green/co2_emissions.csv") %>% 
  mutate(period = as.factor(period))

ggplot(data = filter(co2_emissions, group == "Total"),
       aes(x = period, y = value, group = area_name, fill = group)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_line(size = 1, colour = "#007C9E") +
  geom_point(shape = 21, size = 2.5, colour = "white", fill = "#007C9E") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, NA), labels = comma, position = "right") +
  labs(x = NULL, y = NULL,
       title = "Total carbon dioxide emissions",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, kt CO<sub>2</sub></span>"),
       caption = "Source: Department for Business, Energy & Industrial Strategy",
       fill = NULL) +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10))) 

ggsave("outputs/co2_emissions.eps", device = "eps")
```
</div>

  
<div class="col-md-6">
```{r}
### Admissions to residential and nursing care

residential_home_admissions <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/targeted/residential_home_admissions.csv") %>% 
  filter(area_name == "Trafford")

ggplot(residential_home_admissions, aes(x = period, y = value)) +
  geom_col(fill = "#007C9E") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, NA), position = "right") +
  labs(x = NULL, y = NULL,
    title = "Admissions to residential and nursing care",
    subtitle = paste0("<span style = 'color:#757575;'>Trafford, per 100,000 population</span>"),
    caption = "Source: NHS Digital") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.ontop = TRUE,            
        panel.background = element_rect(color = NA, fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10))) 

ggsave("outputs/residential_home_admissions.eps", device = "eps")
```
</div>
</div>

<div class="row">
<div class="col-md-6">
```{r}
### Delayed transfers of care

dtoc <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/targeted/dtoc.csv") %>% 
  filter(area_name == "Trafford")

ggplot(dtoc, aes(x = period, y = value, group = area_name)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_line(size = 1, colour = "#007C9E") +
  geom_point(shape = 21, size = 2.5, colour = "white", fill = "#007C9E") +
  scale_x_date(expand = c(0.005, 0.005), date_labels = "%d-%b", breaks = "3 months") +
  scale_y_continuous(expand = c(0.005, 0.005), limits = c(0, 40), label = comma, position = "right") +
  labs(x = NULL, y = NULL,
       title = "Delayed Transfers of care",
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, daily beds attributable to social care</span>"),
       caption = "Source: NHS England") +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        axis.text.x = element_text(angle = 90)) 

ggsave("outputs/dtoc.eps", device = "eps")
```
</div>
  
<div class="col-md-6">
```{r}
### Police recorded crime
crime_rate <- read_csv("https://github.com/traffordDataLab/dashboard/raw/master/data/pride/crime_rate.csv") %>% 
  filter(area_name == "Trafford", period %in% c("2018", "2019"), 
         group != "Total recorded crime") %>% 
  mutate(value = as.numeric(value),
         group = fct_rev(factor(group)))

ggplot() +
  geom_segment(
    data = select(crime_rate, group, value, period) %>% 
      group_by(group) %>% 
      summarise(start = range(value)[1], end = range(value)[2]) %>% 
      ungroup(),
    aes(x = start, xend = end, y = group, yend = group), 
    color = "#e3e2e1", size = 2) +
  geom_point(
    data = select(crime_rate, group, period, value),
    aes(x = value, y = group, color = factor(period)),
    size = 4) +
  scale_x_continuous(expand = c(0.005, 0.005), labels = comma) +
  scale_color_manual(values = c("#9fcedb", "#007c9e"),
                     labels = c("2018", "2019")) +
  labs(x = NULL, y = NULL, 
       title = "Police recorded offences", 
       subtitle = paste0("<span style = 'color:#757575;'>Trafford, rate per 1,000 population</span>"),
       caption = "Source: Office of National Statistics", 
       colour = NULL) +
  theme_minimal(base_size = 14) +
  theme(plot.margin = unit(rep(0.5, 4), "cm"),
        panel.grid.major.x = element_line(size = 0.5, color = "#cbcbcb"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 14, face = "bold"),
        plot.subtitle = element_markdown(size = 12, margin = margin(b = 20)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10)),
        legend.position = c(0.85, 1.1),
        legend.direction = "horizontal",
        axis.text.y = element_text(face = "bold", hjust = 0)) +
  expand_limits(x = c(0, 35))

ggsave("outputs/crime_rate.eps", device = "eps")
```
</div>
</div>

